/*
 * This source file was generated by the Gradle 'init' task
 */
package projectonline;

public class App {
    public String getGreeString() {
        return "Hello World";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeString());
    }
}

